name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bazel build //...
      - run: bazel test //...

  release:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - run: bazel run --define=IMAGE_TAG=$IMAGE_TAG //cmd/bep2prom:push_image
        env:
          IMAGE_TAG: latest
