name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: bazel build //...
      - run: bazel test //...

  release:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - run: IMAGE_TAG=latest bazel build //cmd/bep2prom:push_image
